const SESSION_ACTION_TYPES = {
    SET_SESSION_ID: "SET_SESSION_ID",
    SET_SESSION_PASSWORD: "SET_SESSION_PASSWORD",
    SET_SESSION_LINK: "SET_SESSION_LINK",
    SET_SESSION_HOST: "SET_SESSION_HOST",
    SET_SESSION_MEMBERS:"SET_SESSION_MEMBERS",
}

export default SESSION_ACTION_TYPES